Add reusable workflow for Markdown testing
evoila/GitHub-Actions pull request #6
Opened 2023-03-10 01:41 UTC by kalrish

This pull request introduces a reusable workflow for Markdown testing with [markdownlint-cli2](https://github.com/DavidAnson/markdownlint-cli2) and also sets up a non-reusable workflow that uses it in this repository.

2023-03-14 14:46 UTC, EduardSchwarzkopf requested changes
adjust comments and then this can be merged

2023-03-14 14:54 UTC, EduardSchwarzkopf requested changes
Add a test to check if the action is a reusable action and then check for the `resuable-` prefix.

2023-03-15 13:41 UTC, s3Bucket commented on .github/workflows/change_proposal_testing.yaml
> +    name: Check that names of reusable workflow files start with "reusable-"
Einzahl, jede Datei hat nur einen Namen ("The name of reusable Files...")

2023-03-15 13:41 UTC, s3Bucket commented on .github/workflows/change_proposal_testing.yaml
> +        name: Check that names of reusable workflow files start with "reusable-"
Einzahl, jede Datei hat nur einen Namen ("The name of reusable Files...")

2023-03-15 13:55 UTC, s3Bucket submitted a review, later dismissed

2023-03-15 14:25 UTC, kalrish commented on .github/workflows/README.md
> +The name of reusable workflow files begins with "reusable-".
I did :).

2023-03-15 14:25 UTC, EduardSchwarzkopf approved these changes

2023-03-15 14:26 UTC, merged